steps:
- id: 'deploy cloud function upload_csv'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - upload_csv
  - --quiet
  - --gen2
  - --memory=2GB
  - --timeout=300
  - --region=us-central1
  - --source=cloud_functions/upload_csv
  - --entry-point=upload_csv
  - --trigger-bucket=csv-landing-ml-spez-ccai
  - --env-vars-file=cloud_functions/upload_csv/.env.yaml
  - --runtime=python311
  - --service-account=ml-spez@ml-spez-ccai.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY